# Mockery configuration file for DefraDB.

with-expecter: true

quiet: False

disable-version-string: True

log-level: "info"

dry-run: False

mockname: "{{.InterfaceName}}"

# Makes files names lower case, snake.
filename: "{{.InterfaceNameSnake}}.go"

outpkg: mocks

packages: # Packages and their interfaces to generate mocks for.
    github.com/ipfs/go-datastore/query:
        config:
            dir: "./datastore/mocks"
        interfaces:
            Results:

    github.com/sourcenetwork/defradb/datastore:
        config:
            dir: "./datastore/mocks"
        interfaces:
            DAGStore:
            DSReaderWriter:
            RootStore:
            Txn:
            Blockstore:

    github.com/sourcenetwork/defradb/client:
        config:
            dir: "./client/mocks"
        interfaces:
            DB:
            Collection:

    github.com/sourcenetwork/defradb/internal/db/fetcher:
        config:
            dir: "./internal/db/fetcher/mocks"
        interfaces:
            Fetcher:
            EncodedDocument:
